server.port=9000
server.servlet.context-path=/
spring.config.activate.on-profile=prod
spring.messages.properties-charset=UTF-8

# database
spring.datasource.hikari.first.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.hikari.first.jdbc-url=jdbc:log4jdbc:postgresql://192.168.0.24:5432/safewizpro
spring.datasource.hikari.first.username=safewizpro
spring.datasource.hikari.first.password=esg2024
spring.datasource.hikari.first.type=com.zaxxer.hikari.HikariDataSource

# file 개발실/■ Project/ESG경영/ESG_File_Upload/safewizpro
file.nas.fo-path=\uAC1C\uBC1C\uC2E4/\u25A0 Project/ESG\uACBD\uC601/ESG_File_Upload/safewizpro
spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB
spring.servlet.multipart.enabled=true

# log
logging.config=classpath:log4j/log4j2_prod.xml
