# framework setting
spring.application.name=i-framework
spring.application.version=1.0.0
spring.output.ansi.enabled=always
spring.banner.location=classpath:templates/banner.txt
spring.main.allow-circular-references=true
spring.profiles.active=dev
spring.messages.basename=message/exception
spring.messages.encoding=UTF-8
spring.messages.properties-charset=UTF-8
logging.charset.console=UTF-8
spring.config.encoding=UTF-8
logging.charset.file=UTF-8

# JPA
spring.jpa.open-in-view=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.hibernate.ddl-auto=update

# RestTemplate
spring.restTemplate.factory.readTimeout=5000
spring.restTemplate.factory.connectTimeout=3000
spring.restTemplate.httpClient.maxConnTotal=100
spring.restTemplate.httpClient.maxConnPerRoute=5

# Thymeleaf
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.surfix=html
spring.thymeleaf.mod=HTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.order=0

# mail
spring.mail.host=mail.officehub.kr
spring.mail.port=25
spring.mail.username=rmadmin@i-gns.co.kr
spring.mail.password=!Gns25459
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false

# password reset
user.default-status=waiting
user.reset-password-url=http://localhost:5173/resetUserPs?key=
user.remember-user-id=2592000

# JWT
jwt.secretKey=WQJEQIEQWIEJQWID21312JMDKWQI99381DJWI1930D
jwt.secretKey.api=AbC93JkLmNqPWX8273sDfTqzYvRBxE91LmKpWzvEtgMqUiDpHdXJuPZoMfGBcNaQh
# 1 hour
#jwt.access.expiration=3600000
# 7 days
# When multiple browsers are displayed at the same time, problems due to cookie value sharing need to be taken and changed.
jwt.access.expiration=604800000
jwt.access.header=Authorization
jwt.api.header=Authorization-API
jwt.refresh.expiration=2592000000
jwt.refresh.header=Authorization-refresh
jwt.invite.expiration=2592000000
jwt.verify.expiration=1800000
jwt.initialize.expiration=600000

# SSO
sso.enabled=false
sso.auth=http://localhost:9000

# file
file.upload-dir=C:/src/esg
file.max-size=10737418240
file.allow-delete=true
file.target=nas
file.nas.ip=192.168.0.40
file.nas.user=iljoouser
file.nas.pass=&Gns1234*00
file.nas.share-folder=FileServer

# encrypt key
external-encrypt.key=SCFOZXQyMDIw
external-encrypt.secret-key-factory=PBKDF2WithHmacSHA1
external-encrypt.cipher=AES/CBC/PKCS5Padding

# MSDS
msds.url=https://msds.kosha.or.kr/openapi/service/msdschem
msds.key.encoding=4QeNdF3rnMBb16aF2Saf2wY7iS7YUrgkpaWNQTP3A8j8lnALHMyLxdgqNx%2BROBs3inLElfmLjSeZTMq%2FcHeKVA%3D%3D
msds.key.decoding=4QeNdF3rnMBb16aF2Saf2wY7iS7YUrgkpaWNQTP3A8j8lnALHMyLxdgqNx+ROBs3inLElfmLjSeZTMq/cHeKVA==

# date format
dateFormat=yyyy.MM.dd
