fcm.apiurl=https://fcm.googleapis.com/v1/projects/safewiz-pro/messages:send

#OpenWeather Api
weather.currentWeather.apiUrl=http://api.openweathermap.org/data/2.5/weather
weather.shortTermWeather.apiUrl=http://api.openweathermap.org/data/2.5/forecast
weather.apiKey=8f3f7b217f784989c575f5f9e6a7b37b

#KakaoLocal Api
local.apiURl=https://dapi.kakao.com/v2/local/search/address.json
local.apiKey=66e4673857d3872c50d9617e3d900e8b

custom.environment.init-password=012345

#SmartSearch Open Api 
legal.apiUrl=https://apis.data.go.kr/B552468/srch
legal.apiKey.encoding=Erj6WtuItbM2Ad%2BWxPqB3hkwmgLCjAsrcecxlc8KWkCR6NBTUUseayt4wX1GVcly0I8Pf2vpZp0CLAhKiZewvQ%3D%3D
legal.apiKey.decoding=Erj6WtuItbM2Ad+WxPqB3hkwmgLCjAsrcecxlc8KWkCR6NBTUUseayt4wX1GVcly0I8Pf2vpZp0CLAhKiZewvQ==

